updated the release process

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -13,6 +13,15 @@ if [ "$BRANCH" = "production" ]; then
   exit 255
 fi
 
+if [ "$BRANCH" = "development" ]; then
+  echo
+  echo "You cannot commit directly to the development branch."
+  echo "Instead create a feature branch and commit your changes to it."
+  echo "Then push your feature branch to GitHub and create a pull request."
+  echo
+  exit 255
+fi
+
 # For all other branches, run the pre-commit checks using lint-staged.
 if npm run check:staged; then
   echo "Done."
