finished hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,6 +2,18 @@
 
 echo "Running FarmData2 pre-commit checks..."
 
+# Prevent commits to the production branch
+BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+if [ "$BRANCH" = "production" ]; then
+  echo
+  echo "You cannot commit directly to the production branch."
+  echo "The production branch should only be updated by merging development into it."
+  echo "This operation should only be performed by maintainers."
+  echo
+  exit 255
+fi
+
+# For all other branches, run the pre-commit checks using lint-staged.
 if npm run check:staged; then
   echo "Done."
   echo "Making the commit."
